/* QUERY 1 -- Listar o número de departamentos em cada país  */

SELECT COUNTRY_NAME, COUNT( DISTINCT DEPARTMENT_ID ) AS NR_DEPARTMENTS
FROM COUNTRIES C, DEPARTMENTS D, LOCATIONS L
WHERE D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID = C.COUNTRY_ID
group by COUNTRY_NAME ORDER BY NR_DEPARTMENTS desc;


/* QUERY 2 -- Listar o número de employees em cada país */

SELECT COUNTRY_NAME, COUNT( DISTINCT EMPLOYEE_ID ) AS NR_EMPLOYEES
FROM COUNTRIES C, DEPARTMENTS D, LOCATIONS L, EMPLOYEES E
WHERE D.LOCATION_ID = L.LOCATION_ID AND L.COUNTRY_ID = C.COUNTRY_ID
  AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
group by COUNTRY_NAME ORDER BY NR_EMPLOYEES desc;


/* QUERY 3 -- Pessoa que ganha mais */

SELECT FIRST_NAME, LAST_NAME , SALARY, JOB_TITLE
    FROM EMPLOYEES E
        JOIN JOBS J on E.JOB_ID = J.JOB_ID
            WHERE E.SALARY =(SELECT MAX(SALARY) FROM EMPLOYEES);


/* QUERY 4 -- Pessoa que ganha menos */

SELECT FIRST_NAME, LAST_NAME , SALARY, JOB_TITLE
    FROM EMPLOYEES E
        JOIN JOBS J on E.JOB_ID = J.JOB_ID
            WHERE E.SALARY =(SELECT MIN(SALARY) FROM EMPLOYEES);
            
            
/* QUERY 5 -- Pessoa há mais tempo na empresa */

SELECT FIRST_NAME , LAST_NAME , HIRE_DATE ,floor(months_between( CURRENT_DATE , HIRE_DATE ) /12) AS NR_YEARS_WORKING
    FROM EMPLOYEES
        WHERE HIRE_DATE =(SELECT MAX(HIRE_DATE) FROM EMPLOYEES);


/* Query 6 -- Pessoa há menos tempo na empresa */

SELECT FIRST_NAME , LAST_NAME , HIRE_DATE ,floor(months_between( CURRENT_DATE , HIRE_DATE ) /12) AS NR_YEARS_WORKING
    FROM EMPLOYEES
        WHERE HIRE_DATE =(SELECT MIN(HIRE_DATE) FROM EMPLOYEES);
        
        
/* QUERY 7 -- Ordenar a profissão pelo número de employees */

SELECT JOB_TITLE, COUNT( DISTINCT EMPLOYEE_ID ) AS NR_EMPLOYEES
FROM JOBS J, EMPLOYEES E
WHERE J.JOB_ID = E.JOB_ID
group by JOB_TITLE ORDER BY NR_EMPLOYEES desc;


/* Querie 8 -- Listar o número de pessoas que trabalham em cada departamento por odem */

SELECT D."DEPARTMENT_NAME" , COUNT (E.EMPLOYEE_ID)  Nr_Empregados
    FROM EMPLOYEES E
        RIGHT JOIN DEPARTMENTS D ON D."DEPARTMENT_ID" = E."DEPARTMENT_ID"
            GROUP BY D.DEPARTMENT_NAME
                ORDER BY Nr_Empregados DESC;
                
                
/* Querie 9 -- Listar Salário médio por departamento */

SELECT DEPARTMENTS.DEPARTMENT_NAME Departamento, AVG(SALARY) Media FROM  EMPLOYEES, DEPARTMENTS
WHERE DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
GROUP BY EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
ORDER BY Media ASC;


/* Querie 10 -- Listar o histórico de cada employee */

SELECT E.FIRST_NAME EMPLOYEE_FIRST, E.LAST_NAME EMPLOYEE_LAST, J.START_DATE, J.END_DATE, JB.JOB_TITLE JOB, D.DEPARTMENT_NAME DEPARTMENT  FROM JOB_HISTORY J
    JOIN DEPARTMENTS D on D.DEPARTMENT_ID = J.DEPARTMENT_ID
        JOIN EMPLOYEES E on E.EMPLOYEE_ID = J.EMPLOYEE_ID
            JOIN JOBS JB on JB.JOB_ID = J.JOB_ID;


/* Querie 11 -- Listar Salário médio por profissão */

SELECT JOBS.JOB_TITLE Profissão, AVG(SALARY) Media FROM EMPLOYEES, JOBS
WHERE JOBS.JOB_ID = EMPLOYEES.JOB_ID
GROUP BY EMPLOYEES.JOB_ID, JOB_TITLE
ORDER BY Media ASC;

